pluginManagement {
    repositories {
        gradlePluginPortal()

        maven {
            url = uri("https://maven.pkg.github.com/404-Factory/build-logic")
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: "x-token"
                password = System.getenv("GITHUB_TOKEN") ?: ""
            }
        }
    }

    plugins {
        id "com.factory.spring-application-conventions" version "1.0.5"
        id "com.factory.maven-consumer-conventions" version "1.0.5"
    }
}

rootProject.name = 'anomaly-service'